language: python
python:
  - "2.7"
  - "3.3"
  - "pypy"

# command to install dependencies
install: "pip install -e ./"

# command to run tests
script: nosetests --verbose clearskies/test/*.py --with-coverage --cover-package clearskies --cover-branches
